#!/bin/bash

echo ****************{{{{{{{{{{{{{{hello world *************______________
echo -e "\e[31mMESSAGE\e[0m"
echo -e "\e[32mMESSAGE\e[0m"
echo -e "\e[33mMESSAGE\e[0m"
echo -e "\e[34mMESSAGE\e[0m"